outway: discover services via directory
Also changed the docker build strategy to not fail on broken sourcecode.

diff --git a/directory/Dockerfile b/directory/Dockerfile
--- a/directory/Dockerfile
+++ b/directory/Dockerfile
@@ -2,15 +2,23 @@
 FROM golang:1-alpine AS build
 
 # Install build tools.
-RUN apk add --update make git
+RUN apk add --update make git protobuf
 
-# Install modd, which is used within docker-compose.
-RUN go get github.com/cortesi/modd/cmd/modd
+# Install go-based dependencies and tools
+RUN go get \
+        github.com/cortesi/modd/cmd/modd \
+        google.golang.org/grpc \
+        github.com/golang/protobuf/protoc-gen-go \
+        github.com/gogo/protobuf/protoc-gen-gogofast \
+        github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway \
+        github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
 
-# Add code and build.
+# Add code.
 COPY . /go/src/github.com/VNG-Realisatie/nlx
 WORKDIR /go/src/github.com/VNG-Realisatie/nlx/directory
-RUN make
+
+# Ignore failing make to allow this stage to complete even when there are errors in the sourcecode.
+RUN make || true 
 
 
 # Release binary on latest alpine image.
diff --git a/outway/Dockerfile b/outway/Dockerfile
--- a/outway/Dockerfile
+++ b/outway/Dockerfile
@@ -10,7 +10,9 @@ RUN go get github.com/cortesi/modd/cmd/modd
 # Add code and build.
 COPY . /go/src/github.com/VNG-Realisatie/nlx
 WORKDIR /go/src/github.com/VNG-Realisatie/nlx/outway
-RUN make
+
+# Ignore failing make to allow this stage to complete even when there are errors in the sourcecode.
+RUN make || true 
 
 
 # Release binary on latest alpine image.
